:output:
  Profile:
    :options:
      :fields:
        - id
        - user_id
        - first_name
        - last_name
        - city
  User:
    :options:
      :fields:
        - id
        - email
        - sign_in_count
