:output:
  Profile:
    :options:
      :fields:
        - id
        - user_id
        - display_name
        - points
        - nps
        - snippets

  User:
    :options:
      :fields:
        - id
        - email
        - rank
  Debate:
    :options:
      :fields:
        - id
        - affirmative_id
        - negative_id
        - creator_id
        - challenger_id
        - status
        - resolution
