:output:
  Profile:
    :options:
      :fields:
        - id
        - user_id
        - display_name
        - rank
        - city
        - profile_bonus
        - debate_points
        - civility_points
        - points

  User:
    :options:
      :fields:
        - id
        - email
        - rank
