:output:
  Profile:
    :options:
      :fields:
        - id
        - user_id
        - first_name
        - last_name
        - city
  User:
    :options:
      :fields:
        - id
        - email
        - profile_bonus
        - snippet_bonus
        - points
        - rank
